=== maartendekker1998/OU_jabberpoint/JabberPoint/jabberpoint.dtd
<!--
 Document Type Definition voor JabberPoint presentaties
 $Id$
 -->
<!ELEMENT presentation (metadata*,slide+)>

<!ELEMENT metadata (#PCDATA)>
<!ATTLIST metadata kind CDATA #REQUIRED>

<!ELEMENT presenter (#PCDATA)>
<!ELEMENT showtitle (#PCDATA)>
<!ELEMENT slide (title, item*)>
<!ELEMENT title (#PCDATA)>

<!ATTLIST slide transitions CDATA #REQUIRED>
<!ELEMENT item (#PCDATA|item)*>

<!ATTLIST item kind CDATA #REQUIRED>
<!ATTLIST item font CDATA #IMPLIED>
<!ATTLIST item fontsize CDATA #IMPLIED>
<!ATTLIST item color CDATA #IMPLIED>

<!ATTLIST item level CDATA #REQUIRED>

=== maartendekker1998/OU_jabberpoint/JabberPoint/demo_nl.xml
<?xml version="1.0"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
	<metadata kind="presenter">Bart &amp; Maarten</metadata>
	<metadata kind="showtitle">JabberPoint Presentatie - Open Universiteit</metadata>

	<slide transitions="false">
		<title font="Arial" fontsize="60" color="#303338">JabberPoint Demo Presentatie (NL)</title>
		<item kind="text" level="1">Welkom bij JabberPoint!</item>
		<item kind="image" level="1">D:\ou\OU_jabberpoint\JabberPoint\nl.png</item>
		<item kind="text" level="1">Geschreven door:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Maarten Dekker</item>
			<item kind="text" level="2">Bart Janssen</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Besturing:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Switchen van dia's: ← &amp; → </item>
			<item kind="text" level="2">Als een dia transities heeft:</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">Loop door de inhoud met behulp van: ↑ &amp; ↓</item>
				<item kind="text" level="3">Ga naar het begin of einde van de dia met: Home &amp; End</item>
			</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="image" level="3">D:\ou\OU_jabberpoint\JabberPoint\ou.png</item>
		<item kind="text" level="1"> </item>
	</slide>

	<slide transitions="true">
		<title font="Arial" fontsize="60" color="#303338">Transitie oefening (druk op ↓)</title>
		<item kind="text" level="1">Je hebt het eerste content gerendered! Druk nu opnieuw op ↓</item>
		<item kind="text" level="1">Je hebt nu een blok gerendered</item>
		<item kind="text" level="2">Zoals je kan zien, kan je gehele blokken met items renderen</item>
		<item kind="text" level="2">Het bevat alle content die een hoger level heeft dan de orginele</item>
		<item kind="text" level="2">Druk nu op 'End'</item>
		<item kind="text" level="1">Dit renderd het overige van de dia</item>
		<item kind="text" level="1">Je kan terug door de items gaan door gebruik te maken van:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">↑ om stap voor stap omhoog te gaan</item>
			<item kind="text" level="2">'Home' om terug naar het begin van de slide te gaan</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="2">(genoeg oefening? ga naar de volgende dia!)</item>
	</slide>

	<slide transitions="false">
		<title font="Arial" fontsize="60" color="#303338">Menu overzicht</title>
		<item kind="text" level="1">Als je geen toetsenbord hebt, gebruik dan het Menu!</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Je kan de volgende selectie menu's gebruiken:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Application</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">om een nieuwe JabberPoint presentatie te laden</item>
				<item kind="text" level="3">om JabberPoint af te sluiten</item>
			</item>
			<item kind="text" level="2">Slide</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">om te kunnen switchen tussen dia's</item>
			</item>
			<item kind="text" level="2">Content</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">om over de content te itereren</item>
				<item kind="text" level="3">om naar het begin of einde van de dia te gaan</item>
			</item>
			<item kind="text" level="2">Help</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">om informatie over JabberPoint te zien</item>
				<item kind="text" level="3">om informatie te zien over probleemoplossingen</item>
			</item>
		</item>
	</slide>

	<slide transitions="false">
		<title font="Arial" fontsize="60" color="#303338">Stijl Oefening</title>
		<item kind="text" level="1">Stijlen kunnen gezet worden voor content en de dia title:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Lettertype (het OS moet deze wel geïnstalleerd hebben)</item>
			<item kind="text" level="2">Grote voor de grote van het lettertype</item>
			<item kind="text" level="2">Kleur voor de kleur van het lettertype</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Een paar voorbeelden:</item>
		<item kind="text" font="Comic Sans MS" fontsize="24" color="#fc0317" level="2">Dit is comic sans 24 in rood</item>
		<item kind="text" font="Algerian" fontsize="35" color="#030ffc" level="2">Dit is algerian 35 in blauw</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Met stijlen kan ook een bulletlist icoon gezet worden:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Deze bullet list heeft een ● als icoon</item>
		</item>
		<item kind="bulletlist" bullet="◇" level="2">
			<item kind="text" level="2">Deze bullet list heeft ◇ als icoon</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Voor meer info, zie Help → Troubleshooting</item>
	</slide>
</presentation>

=== maartendekker1998/OU_jabberpoint/JabberPoint/demo.xml
<?xml version="1.0"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
	<metadata kind="presenter">Bart &amp; Maarten</metadata>
	<metadata kind="showtitle">JabberPoint Presentation - Open Universiteit</metadata>

	<slide transitions="false">
		<title font="Arial" fontsize="60" color="#303338">JabberPoint Demo Presentation</title>
		<item kind="text" level="1">Welcome to JabberPoint!</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Written by:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Maarten Dekker</item>
			<item kind="text" level="2">Bart Janssen</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Controls:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Switching Slides: ← &amp; → </item>
			<item kind="text" level="2">If slides have transitions:</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">Go through content by using: ↑ &amp; ↓</item>
				<item kind="text" level="3">Go to begin or end of the slide by using: Home &amp; End</item>
			</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="image" level="3">D:\ou\OU_jabberpoint\JabberPoint\ou.png</item>
		<item kind="text" level="1"> </item>
	</slide>

	<slide transitions="true">
		<title font="Arial" fontsize="60" color="#303338">Transition tutorial (press ↓)</title>
		<item kind="text" level="1">You've rendered the first item! Now press ↓ again</item>
		<item kind="text" level="1">You've rendered a chunk</item>
		<item kind="text" level="2">As you can see you can also render a chunk of items</item>
		<item kind="text" level="2">It contains all items with a higher level than the root</item>
		<item kind="text" level="2">Now press 'End'</item>
		<item kind="text" level="1">This renders the entire slide</item>
		<item kind="text" level="1">You can go back though the items by using:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">↑ to go backwards step by step</item>
			<item kind="text" level="2">'Home' to go back to the start of the slide</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="2">(enough practice? go to the next slide!)</item>
	</slide>

	<slide transitions="false">
		<title font="Arial" fontsize="60" color="#303338">Menu overview</title>
		<item kind="text" level="1">When you don't have a keyboard, just use the Menu!</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">You can use the following dropdown menus:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">Application</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">to load a new JabberPoint presentation</item>
				<item kind="text" level="3">to exit JabberPoint</item>
			</item>
			<item kind="text" level="2">Slide</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">to go back and forth between slides</item>
			</item>
			<item kind="text" level="2">Content</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">to iterate over content</item>
				<item kind="text" level="3">to go to the beginning or end of the slide</item>
			</item>
			<item kind="text" level="2">Help</item>
			<item kind="bulletlist" bullet="○" level="3">
				<item kind="text" level="3">to see information about JabberPoint</item>
				<item kind="text" level="3">to read troubleshooting information</item>
			</item>
		</item>
	</slide>

	<slide transitions="false">
		<title font="Arial" fontsize="60" color="#303338">Styling Tutorial</title>
		<item kind="text" level="1">Styles can be set for content and slide-titles:</item>
		<item kind="bulletlist" bullet="●" level="1">
			<item kind="text" level="2">Font can be set (the OS must have the font installed)</item>
			<item kind="text" level="2">Fontsize can be set</item>
			<item kind="text" level="2">Color can be set</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">A few examples:</item>
		<item kind="text" font="Comic Sans MS" fontsize="24" color="#fc0317" level="2">This is comic sans 24 in red</item>
		<item kind="text" font="Algerian" fontsize="35" color="#030ffc" level="2">This is algerian 35 in blue</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">Styles can also be used to freely set the bulletlist icon:</item>
		<item kind="bulletlist" bullet="●" level="2">
			<item kind="text" level="2">This bullet list has ● as bullet</item>
		</item>
		<item kind="bulletlist" bullet="◇" level="2">
			<item kind="text" level="2">This bullet list has ◇ as bullet</item>
		</item>
		<item kind="text" level="1"> </item>
		<item kind="text" level="1">For more info see Help → Troubleshooting</item>
	</slide>
</presentation>
